#pragma kernel CSMain
#pragma kernel CullInstances
#include <UnityShaderVariables.cginc>

struct GrassInstanceData
{
    float3 position;
    float rotationY;
    float2 scale;
};

StructuredBuffer<GrassInstanceData> _AllInstances;
AppendStructuredBuffer<GrassInstanceData> _VisibleInstances;

RWStructuredBuffer<uint> _ArgsBuffer;

float4 _FrustumPlanes[6];   //xyz = normal ,w = distance
bool EnableFrustumCulling;

//#pragma multi_compile VGTYPE_GRASS VGTYPE_TREE VGTYPE_SHURB

bool DistanceTest(float3 position)
{
    float4 near = _FrustumPlanes[4];
    float signedDist = dot(near.xyz,position) + near.w;
    if(signedDist > 300 || signedDist < 0.1)
    {
        return false;
    }
    
    return true;
}

bool FrustumTest(float3 position)
{
    [unroll]
    for(int i=0;i<6;i++)
    {
        float4 plane = _FrustumPlanes[i];   //xyz:normal w:distance
        float d = dot(plane.xyz,position) + plane.w + 2.0;
        if(d < 0.0)
        {
            return false;
        }
    }
    return true;
}

[numthreads(64,1,1)]
void CSMain(uint id : SV_DispatchThreadID)
{
    if(id >= _AllInstances.Length)
        return;
   
    GrassInstanceData inst = _AllInstances[id];

    float3 pos = inst.position;
    
    if(EnableFrustumCulling)
    {
        if(DistanceTest(pos) && FrustumTest(pos))
        {
            _VisibleInstances.Append(inst);
            InterlockedAdd(_ArgsBuffer[1],1);
        }
    }
    else
    {
        _VisibleInstances.Append(inst);
        InterlockedAdd(_ArgsBuffer[1],1);
    }
}

struct ChunkInfo
{
    uint guid;
    float3 center;
    float3 size;
    uint startIndex;
    uint count;
};
StructuredBuffer<ChunkInfo> _VisibleChunkInfos;
uint _ChunkCount;


[numthreads(64,1,1)]
void CullInstances(
    uint3 dispatchThreadID   : SV_DispatchThreadID,
    uint3 groupID            : SV_GroupID,
    uint3 groupThreadID      : SV_GroupThreadID,
    uint  groupIndex         : SV_GroupIndex)
{
    int chunkIndex = groupID.x;
    if(chunkIndex >= _ChunkCount) return;
    ChunkInfo chunk = _VisibleChunkInfos[chunkIndex];

    uint localInstanceIndex = groupID.y * 64 + groupThreadID.x;
    if(localInstanceIndex >= chunk.count) return;

    uint globalInstanceIndex = chunk.startIndex + localInstanceIndex;

    // // 安全检查，防止越界读取
    // uint totalInstances, stride;
    // _AllInstances.GetDimensions(totalInstances, stride);
    // if(globalInstanceIndex >= totalInstances) return;

    GrassInstanceData data = _AllInstances[globalInstanceIndex];

    float3 position = data.position;

    if(FrustumTest(position))
    {
        _VisibleInstances.Append(data);
        InterlockedAdd(_ArgsBuffer[1],1);
    }
}